config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

  has_many :user_tasks
  has_many :users, through: :user_tasks

  enum status: {untouched: 0, started: 1, completion: 2}
  enum priority: {low: 0, normal: 1, high: 2}
  validates :name, presence: true
  validates :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_tasks
  has_many :tasks, through: :user_tasks
end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/concerns/common_utils.rb
module CommonUtils
  def require_valid_params(instance)
    return if instance.valid?
    flash.now[:danger] = instance.errors.full_messages
    case params[:action].to_sym
      when :create
        return render :new
      when :update
        return render :edit
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include CommonUtils
  before_action :load_resource

  def index
    @q = Task.ransack(params[:q])
    @tasks = @q.result.page(params[:page]).per(10)
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    return if require_valid_params(@task)
    if @task.save!
      redirect_to @task, success: ['task created']
    end
  end

  def edit; end

  def update
    @task.attributes = task_params
    return if require_valid_params(@task)
    @task.save
    redirect_to @task, success: ['task updated']
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, success: ['task delete']
  end

  private

  def task_params
    params.require(:task).permit(
      :name, :body, :limits, :status, :priority
    )
  end

  def load_resource
    case params[:action].to_sym
      when :create
        @task = Task.new(task_params)
      when :show, :edit, :update, :destroy
        @task = Task.find(params[:id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.slim
- flash.each do |message_type, messages|
  .alert class="alert-#{message_type}"
    - messages.each do |msg|
      li
        = msg

app/views/layouts/_header.html.slim
header
  nav.navbar.navbar-expand-lg.navbar-light.bg-light
    = link_to 'HOME', root_path, class: 'navbar-brand'
    button.navbar-toggler aria-controls="navbarNav" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarNav" data-toggle="collapse" type="button"
      span.navbar-toggler-icon
    #navbarNav.collapse.navbar-collapse
      ul.navbar-nav
        li.nav-item
          = link_to 'タスク一覧', tasks_path, class: 'nav-link'
        li.nav-item
          = link_to 'タスクnew', new_task_path, class: 'nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ElTraining
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    .container
      = render 'layouts/flash'
      = yield

app/views/tasks/_form.html.slim
= form_with model: @task, local: true do |f|
  .form-group.row
    = f.label :name, class:'col-2 col-form-label'
    .col-10
      = f.text_field :name, class:'form-control'
  .form-group.row
    = f.label :body, class:'col-2 col-form-label'
    .col-10
      = f.text_area :body, class:'form-control'
  .form-group.row
    = f.label :limits, class:'col-2 col-form-label'
    .col-10
      = f.date_field :limits, class:'form-control'
  .form-group.row
    = f.label :status, class:'col-2 col-form-label'
    .col-10
      = f.select :status, Task.statuses.keys, {}, class:'form-control'
  .form-group.row
    = f.label :priority, class:'col-2 col-form-label'
    .col-10
      = f.select :priority, Task.priorities.keys, {selected: 'normal'}, class: 'form-control'
  
  = f.submit "登録", class: "btn btn-primary btn-block"

app/views/tasks/_task.html.slim
tr
  td = link_to task.name, task_path(task)
  td = task.limits
  td = task.status
  td = task.priority

app/views/tasks/edit.html.slim
= render 'form'

app/views/tasks/index.html.slim
= link_to 'task new', new_task_path, class: "btn btn-primary"
table.table.table-bordered
  thead
    tr
      th = sort_link(@q, :name)
      th = sort_link(@q, :limit)
      th = sort_link(@q, :status)
      th = sort_link(@q, :priority)
  tbody
    = render @tasks
= page_entries_info @tasks
= paginate @tasks

app/views/tasks/new.html.slim
= render 'form'

app/views/tasks/show.html.slim
h2
  = @task.name
.form-group.row
  .col-2.col-form-label
    p task body
  .col-10
    = @task.body
.form-group.row
  .col-2.col-form-label
    p task limits
  .col-10
    - if @task.limits
      = @task.limits.strftime("%Y-%m-%d")
.form-group.row
  .col-2.col-form-label
    p task status
  .col-10
    = @task.status
.form-group.row
  .col-2.col-form-label
    p task priority
  .col-10
    = @task.priority

= link_to 'edit', edit_task_path(@task), class: "btn btn-primary"
hr

= link_to 'Delete', task_path, method: :delete, class: "btn btn-danger"